# DESENVOLVA UMA LÓGICA QUE LEIA O PESO E ALTURA DE UMA PESSOA E CALCULE SEU IMG E MOSTRE SEUS STATUS.
# DE ACORDO COM A TABELA ABAIO
'''
ABAIXO DE 18.5: ABAIXO DO PESO
ENTRE 18.5 E 25: PESO IDEAL
DE 25 ATÉ 30: SOBREPESO
30 ATÉ 40: OBESIDADE
ACIMA DE 40: OBESIDADE MÓRBIDA
'''