# REFAÇA O DESAFIO 35 DOS TRIÂNGULOS ACRESCENTANDO O RECURSO DE MOSTRAR QUE TIP ODE TRIÂNGULO SERÁ FORMADO:
'''
EQUILÁTERO: TODOS OS LADOS IGUAIS
ISÓSCALES: DOIS LADOS IGUAIS
ESCALENO: TODOS OS LADOS DIFERENTES
'''