print('===== DESAFIO 002 =====')
valor1 = input('Digite algo ao lado: ')
print(f'O tipo primitivo do valor acima é: {type(valor1)}')
print(f'Só tem espaços? {valor1.isspace()}')
print(f'É um número? {valor1.isnumeric()}')
print(f'É alfabético? {valor1.isalpha()}')
print(f'É alfanumérico? {valor1.isalnum()}')
print(f'Está em maiúsculo? {valor1.isupper()}')
print(f'Está em minúsculo? {valor1.islower()}')
print(f'Está capitalizada? {valor1.istitle()}')
print(f'É decimal? {valor1.isdecimal()}')