print('===== DESAFIO 001 =====')
print('Faça uma soma entre dois números')
n1 = int(input("Digite um número para a soma: "))
n2 = int(input("Digite outro número para a soma: "))
r = (n1 + n2)
print(f'A soma entre os números {n1} e {n2} é {r}')